# Generated by Django 2.2 on 2020-07-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='descuento',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='idd',
            field=models.DateField(max_length=50),
        ),
    ]
